### ISSUE TITLE
Reduce the number of warnings in the CI

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/nwb-conversion-tools#486]
@bendichter requested me to work to reduce some warnings. In the last two weeks the number has been reduced from around 600 before any warning reduction related PR to around 300 with #481  

I think that now most of the low hanging fruit has been taken and the remaining ones have to do with other packages or require modify our tests slightly. So this is to document the work that has been done and establish a roadmap ahead:

- [x] dict_deep_update warnings #481
- [x] numpy `np.int` and `np.float` deprecation warnings #459. (there are some PRs in `roiextractors` and `spikeextractors` here as well)
- [x] Warnings for in the spot group creation #466. 

The remaining warnings come from different sources. I list them here in no particular order.

As I mentioned, I think that most of the low-hanging fruit has already been picked and I will add this as low-priority unless @bendichter things it should be higher:
- [x] Deprecationg warning for `scipy.io.matlab.mio5_params` in roi-extractor.
- [x] Warning for non description used in `test_si` (this probably should be solved when we address issue #287
- [ ]  `warn("could not find TwoPhotonSeries, using ImagingExtractor to create an nwbfile")` roiextractors.

As I mentioned, there is also a bunch of errors that come from other libraries. Not clear if they could be solved by updating their version (I think this should be the case for some of the `pandas` warnings).  

Here is a log from running pytest on main on my system for future reference.
[warnings_main.txt](https://github.com/catalystneuro/nwb-conversion-tools/files/8574672/warnings_main.txt)

**Comment by h-mayorquin** [comment]
I think that we done with the most numerous warnings. Looking at the current state of affairs it seems that most of the remaining warnings correspond to the movie interface which I will get rid when I fix them so they run faster ( see #449). Then, the are some warnings corresponding to missing metadata that should be address after #501. 

The only two remaining issues that I think we should settle to close this issue are two pending PRs in `sipkeextractors`:

https://github.com/SpikeInterface/spikeextractors/pull/673
https://github.com/SpikeInterface/spikeextractors/pull/675

Could we merge those so we can close this @alejoe91 @bendichter ?

Then we should be able to close this issue for good.

**Comment by h-mayorquin** [comment]
We are down from 700 to 100 warnings now. The remaining ones seem to be related to lack of metadata and electrode information which should be fixed once we start to systematically add metadata to our examples. Then there is the MovieInterface.
